got core linking without mbed memory wrappers
* used --specs=nosys.specs to resolve undefined reference to 'exit' symbol
* encountered undefined references to symbols such as '__wrap__free_r' when including the auto-generated '-Wl,--wrap' flags so they are temporarily removed from the .flags-ld file (.flags-ld.bak contains all original flags)